[workspace]
members = ["chip8", "chip8_ui"]
resolver = "2"

[profile.release]
strip = true
lto = "thin"
opt-level = 2 # fast and small wasm


# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2


[patch.crates-io]
